In [1]:
# Define the documents as a dictionary where keys are document titles and values are document content
documents = {
    "Article: Pandas Basics": "This article covers the basics of using Pandas in Python.",
    "Tutorial: Data Visualization": "Learn about data visualization techniques with Python libraries.",
    "Case Study: Sales Analysis": "Analyze sales data using Python for a real-world case study."
}

In [45]:
# get the keys of the documents and store it in the list
key_documents = documents.keys()

# display the list of the key documents

key_documents = list(key_documents)
print(key_documents)

['Article: Pandas Basics', 'Tutorial: Data Visualization', 'Case Study: Sales Analysis']


In [14]:
# Extract the category of the key documents and store it 
key_pairs = []
for key in key_documents:
    key_pairs.append(key.split(":"))

categories = []
for pair in key_pairs:
    categories.append(pair[0])

categories

['Article', 'Tutorial', 'Case Study']

In [48]:

# Extract the content values and put them in a list
document_content_list = documents.values()

# Display the list of document content
document_content_list = list(document_content_list)
print(document_content_list)

['This article covers the basics of using Pandas in Python.', 'Learn about data visualization techniques with Python libraries.', 'Analyze sales data using Python for a real-world case study.']


In [49]:
# Gather the set of all unique terms from the list content of document and diplay the result
unique_terms = []

for value in document_content_list:
    for word in value.split():
        unique_terms.append(word)

unique_terms = set(unique_terms)
unique_terms

{'Analyze',
 'Learn',
 'Pandas',
 'Python',
 'Python.',
 'This',
 'a',
 'about',
 'article',
 'basics',
 'case',
 'covers',
 'data',
 'for',
 'in',
 'libraries.',
 'of',
 'real-world',
 'sales',
 'study.',
 'techniques',
 'the',
 'using',
 'visualization',
 'with'}

In [50]:
# create a matrix for the document by using the unique term
doc_term_matrix = {}

# your code here
for word in unique_terms:
    doc_term_matrix[word] = []
    for content in document_content_list:
        if word in content:
            doc_term_matrix[word].append(1)
        else:
            doc_term_matrix[word].append(0)

# display the result of the matrix
doc_term_matrix

{'sales': [0, 0, 1],
 'This': [1, 0, 0],
 'Analyze': [0, 0, 1],
 'about': [0, 1, 0],
 'data': [0, 1, 1],
 'Pandas': [1, 0, 0],
 'with': [0, 1, 0],
 'using': [1, 0, 1],
 'a': [1, 1, 1],
 'visualization': [0, 1, 0],
 'in': [1, 0, 1],
 'the': [1, 0, 0],
 'case': [0, 0, 1],
 'study.': [0, 0, 1],
 'covers': [1, 0, 0],
 'Python.': [1, 0, 0],
 'of': [1, 0, 0],
 'for': [0, 0, 1],
 'Learn': [0, 1, 0],
 'basics': [1, 0, 0],
 'Python': [1, 1, 1],
 'libraries.': [0, 1, 0],
 'real-world': [0, 0, 1],
 'article': [1, 0, 0],
 'techniques': [0, 1, 0]}

In [51]:
x = [1,3,2]
y = [3,2,1]

print(set(x) == set(y))

True


In [58]:
# import the numpy library if it doesn't work you need to install numpy
import numpy as np

docs_array = np.array(document_content_list, dtype='object')

v1 = np.array(doc_term_matrix['the'])    
v2 = np.array(doc_term_matrix['Python'])

print(v1)
print(v2)
print('-------')

# find the documents that have both terms from v1 and v2
v3 = v1 & v2

print(v3)

# display the content document from the result
[doc for doc in v3 * docs_array if doc]

[1 0 0]
[1 1 1]
-------
[1 0 0]


['This article covers the basics of using Pandas in Python.']

In [59]:
# find the document for those have at least one word
v2

array([1, 1, 1])

In [69]:
target = "using"

print("Contents which contain the word {}".format(target))
v4 = np.array(doc_term_matrix[target])
[doc for doc in v4 * docs_array if doc]

Contents which contain the word using


['This article covers the basics of using Pandas in Python.',
 'Analyze sales data using Python for a real-world case study.']